### ISSUE TITLE
Preference: Explicit is better than implicit.

### ISSUE THREAD

**Issue by ldunham1** [mikemalinowski/qute#1]
https://github.com/mikemalinowski/qute/blob/3c5e1c34eba7153ba564910963f5c48c7abd1b4c/qute/__init__.py#L40

Currently implicitly decides that its using python 2 or 3 based on available imports.
As unlikely as it is, you may have matching available module names or identically named backports that could cause issues with the assumption that you're running on Python 2/3.

It might be "safer" to explicitly check the version of python and import from that?

**Comment by mikemalinowski** [comment]
Couldnt agree more... on reflection the approach i took was horrible. Asking for the version info makes far more sense and is far more readable and safe too. 

Thanks!
