### ISSUE TITLE
Minor: tray.ProcessorThread may undesirably catch all exceptions - including KeyboardInterrupt, SystemExit etc

### ISSUE THREAD

**Issue by ldunham1** [mikemalinowski/qute#11]
https://github.com/mikemalinowski/qute/blob/3c5e1c34eba7153ba564910963f5c48c7abd1b4c/qute/extensions/tray.py#L409

Not sure of the benefit of catching all exceptions, but except Exception is usually intended instead.
I would be interesting in understanding the benefit in this case if this is desirable.

**Comment by mikemalinowski** [comment]
switch to (Exception, RuntimeError)

**Comment by ldunham1** [comment]
RuntimeError inherits Exception, so just use exception :)
```
print(RuntimeError.__mro__)
(<type 'exceptions.RuntimeError'>, <type 'exceptions.StandardError'>, <type 'exceptions.Exception'>, <type 'exceptions.BaseException'>, <type 'object'>)
```

**Comment by mikemalinowski** [comment]
aaah ... i am such a noob, thanks for pointing that out! I will get it changed
