### ISSUE TITLE
Minor: Env var contents may have leading/trailing spaces.

### ISSUE THREAD

**Issue by ldunham1** [mikemalinowski/qute#5]
https://github.com/mikemalinowski/qute/blob/3c5e1c34eba7153ba564910963f5c48c7abd1b4c/qute/constants.py#L19

I've hit a few issues before when tokenizing a string when I didnt run str.strip() on each token.
Unsure if os.path.exists will care, but if so, then you may need to do it twice.

**Comment by mikemalinowski** [comment]
ah nice. You're right, i had not considered that. I have put a strip in both places - as its code which only occurs on the modules import i dont think a minor perf hit is a problem.
