### ISSUE TITLE
Minor: Potentially unintentionally adding filepaths to QUTE_STYLE_LOCATIONS.

### ISSUE THREAD

**Issue by ldunham1** [mikemalinowski/qute#6]
https://github.com/mikemalinowski/qute/blob/3c5e1c34eba7153ba564910963f5c48c7abd1b4c/qute/constants.py#L24

os.path.isdir() will check if the path exists AND if its a directory.
Depending on usage, it might be "safer" to use than os.path.exists().

**Comment by mikemalinowski** [comment]
Nice find - i had not even considered that. Switched to os.path.isdir as per your suggestion.
