### ISSUE TITLE
Minor: Suggestion to use os.pathsep instead of hardcoding semi-colon.

### ISSUE THREAD

**Issue by ldunham1** [mikemalinowski/qute#8]
https://github.com/mikemalinowski/qute/blob/3c5e1c34eba7153ba564910963f5c48c7abd1b4c/qute/constants.py#L23

https://docs.python.org/3/library/os.html#os.pathsep

It may improve os compatibility.

**Comment by mikemalinowski** [comment]
Learn something new every day! I didnt know pathsep was a thing!

Updated to use that
